In [1]:
import pandas as pd
df = pd.read_csv('website_traffic.csv')
df

      Source  SessionDuration
0    Organic             8.15
1    Organic            17.28
2     Direct             8.62
3       Paid            17.95
4       Paid            27.04
5       Paid            12.58
6    Organic             7.36
7     Social            29.93
8    Organic            15.78
9     Social             3.64
10  Referral             2.37
11   Organic             4.18
12   Organic            19.20
13   Organic            23.97
14      Paid            13.24
15      Paid             2.84
16    Social            12.07
17    Social            29.89
18   Organic            16.34
19    Social            29.16
20   Organic            17.19
21  Referral             3.11
22  Referral             3.98
23   Organic             4.28
24  Referral            21.02
25  Referral            25.40
26      Paid             3.89
27    Social             8.24
28   Organic            26.97
29    Direct            18.04
30    Direct            18.00
31  Referral             7.76
32    Direct            22.33
33    Direct            24.51
34    Direct             4.82
35  Referral            13.42
36    Direct            20.64
37      Paid            21.82
38      Paid            28.37
39   Organic             8.90
40   Organic             7.76
41      Paid            19.79
42  Referral             3.61
43   Organic            24.75
44    Direct            17.44
45    Social            24.38
46      Paid             4.00
47      Paid            18.99
48   Organic            22.65
49    Direct            17.63

In [5]:
grouped = df.groupby('Source')['SessionDuration'].agg(['sum', 'mean', 'count'])
grouped

             sum       mean  count
Source
Direct    152.03  16.892222      9
Organic   224.76  14.984000     15
Paid      170.51  15.500909     11
Referral   80.67  10.083750      8
Social    137.31  19.615714      7